### ISSUE TITLE
Import OpenRAVE libraries and programs from asibot-main repo

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/openrave-yarp-plugins#26]
This is part of the code reorganization project related to roboticslab-uc3m/asibot-main#28. The following items are scheduled to be imported here and improved upon:

* [/src/libraries/RavePlugins](https://github.com/roboticslab-uc3m/asibot-main/tree/310d5dc/src/libraries/RavePlugins)
* [/src/libraries/RlPlugins/ravebot](https://github.com/roboticslab-uc3m/asibot-main/tree/310d5dc/src/libraries/RlPlugins/ravebot)
* [/src/libraries/TestRaveBotLib](https://github.com/roboticslab-uc3m/asibot-main/tree/310d5dc/src/libraries/TestRaveBotLib)
* [/src/modules/testRaveBot](https://github.com/roboticslab-uc3m/asibot-main/tree/310d5dc/src/modules/testRaveBot)
* [/src/modules/robotDraw](https://github.com/roboticslab-uc3m/asibot-main/tree/310d5dc8cf6c15fb3a4be54dfa3044da10d5e6e6/src/modules/robotDraw)

**Comment by jgvictores** [comment]
Added [/src/modules/robotDraw](https://github.com/roboticslab-uc3m/asibot-main/tree/310d5dc8cf6c15fb3a4be54dfa3044da10d5e6e6/src/modules/robotDraw) to the list, as commented at https://github.com/roboticslab-uc3m/asibot-main/issues/21#issuecomment-298590951.

**Comment by jgvictores** [comment]
As commented [here](https://github.com/roboticslab-uc3m/asibot-main/issues/28#issuecomment-340782713), `YarpOpenraveControlboard` is becoming a good replacement of `ravebot`.

**Comment by jgvictores** [comment]
As commented [here](https://github.com/roboticslab-uc3m/asibot-main/issues/28#issuecomment-347933819), `YarpOpenraveControlboard` is finally a good replacement of `ravebot`. 

Only need to port robotDraw now.

**Comment by jgvictores** [comment]
robotDraw ported as of 35a10406323dd8feb0a1e74c70a36531e2bfb9d1
