### ISSUE TITLE
Error: undefined symbol: add_yarpplugins_plugins

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/openrave-yarp-plugins#28]
Trying to run the example openrave-YarpRobot.py in my personal fork... it breaks showing this:

```bash
teo@teo-oliver:~/repos/rsantos88/openrave-yarp-plugins/examples$ python openrave-YarpRobot.py 
[plugindatabase.h:577 Create] Failed to create name fcl_, interface collisionchecker
[xmlreaders-core.cpp:2591 endElement] failed to create iksolver ik/ikfast0x10000048.Transform6D.x86_64.16_17_18_19_20_21.so
[xmlreaders-core.cpp:2591 endElement] failed to create iksolver ik/ikfast0x10000048.Transform6D.x86_64.22_23_24_25_26_27.so
python: symbol lookup error: /usr/local/lib/openrave0.9-plugins/libOpenraveYarpControlboard.so: undefined symbol: add_yarpplugins_plugins
```

**Comment by jgvictores** [comment]
Could you try the `fix-28-linker-error` branch I just created?
(attempt of fix at 548374990a44864ba2a20b2d802f72c19aad81c8)

**Comment by rsantos88** [comment]
Yes!! It's running perfect now.. thanks @jgvictores !

**Comment by jgvictores** [comment]
Great! Please merge into `develop` if you can.

**Comment by rsantos88** [comment]
yes, of course! :+1:

**Comment by RaulFdzbis** [comment]
I had this same error in a new fresh computer, the solution was again to do the same as in https://github.com/roboticslab-uc3m/openrave-yarp-plugins/commit/548374990a44864ba2a20b2d802f72c19aad81c8. 

Is not this solution merged with develop yet?

**Comment by jgvictores** [comment]
It looks like it has been merged with `develop`, see: https://github.com/roboticslab-uc3m/openrave-yarp-plugins/blob/develop/openraveplugins/OpenraveYarpControlboard/OpenraveYarpControlboard.cpp

Could you do the following? 
- sudo rm /usr/local/lib/openrave0.9-plugins/libOpenraveYarpControlboard
- git pull  # copy+paste output here
- git status # copy+paste output here
- make && sudo make install
- python openrave-YarpRobot.py # copy+paste output here
