### ISSUE TITLE
[teoSim] Implement hand joint

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/openrave-yarp-plugins#32]
_From @jgvictores on May 25, 2015 10:6_

Left and right hand joints currently not implemented in simulator.

_Copied from original issue: roboticslab-uc3m/kinematics-dynamics#10_

**Comment by PeterBowman** [comment]
Keep in mind that teoSim is deprecated. Please update the title accordingly with whatever comes out of #27.

**Comment by jgvictores** [comment]
Plugins use whatever are defined as the manipulator. Moving to https://github.com/roboticslab-uc3m/teo-openrave-models

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/teo-openrave-models#9
