### ISSUE TITLE
How to do a grasping hand for Teo

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/openrave-yarp-plugins#37]
To advance in the correct way with [grasping in openrave](http://openrave.org/docs/0.6.6/openravepy/databases.grasping/), we need to make the actual Teo hand able to open and close like the [barrett hand](https://github.com/rdiankov/openrave/blob/master/src/robots/barretthand.kinbody.xml).
Which are the steps to follow?

**Comment by rsantos88** [comment]
First, I think we need to separate the fingers in three different 3D files..

![hand](https://user-images.githubusercontent.com/15872457/31167472-7906b6e0-a8f2-11e7-9f2d-3b8d6c9f8b5e.jpg)

or.. maybe 6 files? (2 parts per finger..?)

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/QA#31
