### ISSUE TITLE
Move FakeControlboard to yarp-devices

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/openrave-yarp-plugins#54]
The [FakeControlBoard device](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/tree/44296ec7cfadf7f6cbe4a316ce0cbd224b0056a5/libraries/YarpPlugins/FakeControlboard) actually belongs to [roboticslab-uc3m/yarp-devices](https://github.com/roboticslab-uc3m/yarp-devices). We only needed this here because of teoSim:

https://github.com/roboticslab-uc3m/openrave-yarp-plugins/blob/44296ec7cfadf7f6cbe4a316ce0cbd224b0056a5/programs/teoSim/ControlboardContainer.cpp#L66

...which is about to die as a result of #27.

When completed, remember to update unit tests at kinematics-dynamics ([.travis.yaml](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/5f0383af9e5c13fecac8e45e4e9b5bc30e4ac288/.travis.yml#L34) + [doc/kinematics-dynamics-install.md](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/5f0383af9e5c13fecac8e45e4e9b5bc30e4ac288/doc/kinematics-dynamics-install.md#kinematics-dynamics-installation-from-source-code)).

This issue is preceded by 8b4a803 (code & style review, minor refactorization of FCB).

**Comment by jgvictores** [comment]
Given that it doesn't even depend on ColorDebug, maybe we could clean it up a bit and try a PR at YARP?

**Comment by jgvictores** [comment]
PS: Oh, wait! It does depend on ColorDebug, see [here](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/blob/44296ec7cfadf7f6cbe4a316ce0cbd224b0056a5/libraries/YarpPlugins/FakeControlboard/DeviceDriverImpl.cpp#L8).

**Comment by PeterBowman** [comment]
> PS: Oh, wait! It does depend on ColorDebug, see here.

My bad: 4dfa391 :(. We can revert it, though.

> maybe we could clean it up a bit and try a PR at YARP?

For reference: http://yarp.it/classyarp_1_1dev_1_1TestMotor.html.

**Comment by traversaro** [comment]
Little intrusion: there is also https://github.com/robotology/yarp/tree/master/src/devices/fakeMotionControl , even if sadly is not greatly documented/visible as most of devices in YARP.

**Comment by PeterBowman** [comment]
Thanks! I tweaked our unit test at kinematics-dynamics to use *fakeMotionControl* (in [here](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/5f0383af9e5c13fecac8e45e4e9b5bc30e4ac288/test/testBasicCartesianControl.cpp#L26), passing a compulsory `name` option as well), but kept being unable to acquire the `yarp::dev::IVelocityControl` interface handle (crashes [here](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/5f0383af9e5c13fecac8e45e4e9b5bc30e4ac288/libraries/YarpPlugins/BasicCartesianControl/DeviceDriverImpl.cpp#L46)). It does not happen when I upgrade the velocity interface to `yarp::dev::IVelocityControl2` ([ref](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/5f0383af9e5c13fecac8e45e4e9b5bc30e4ac288/libraries/YarpPlugins/BasicCartesianControl/BasicCartesianControl.hpp#L189)).

**Comment by jgvictores** [comment]
@traversaro Thanks for the reference!
@PeterBowman Looks good! I put https://github.com/robotology/yarp/issues/1502 just to keep thing in place. :-)

**Comment by PeterBowman** [comment]
We observed that `fakeMotionControl` does not emulate velocities in position or velocity control mode.
For now, waiting for #27, and then will move `FakeControlboard` to yarp-devices.

**Comment by jgvictores** [comment]
No longer blocked!

**Comment by PeterBowman** [comment]
Done at:

* 9289d7e
* [roboticslab-uc3m/yarp-devices@fafe871...18aa6ab](https://github.com/roboticslab-uc3m/yarp-devices/compare/fafe871...18aa6ab)
* roboticslab-uc3m/kinematics-dynamics@aa9a20c

**Comment by jgvictores** [comment]
Thank you so much!!
