### ISSUE TITLE
YarpOpenraveRGBDSensor publishes fixed positions of obstacles

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/openrave-yarp-plugins#87]
Despite correctly sending information from available depth sensors through the `<prefix>/depthImage:o` port, all coordinates refer to the absolute (fixed) location of obstacles along one of the environment's axes. That is, it doesn't matter where the sensor is located at. It's worth noting that a quick glimpse at yarpview's output will not reveal any of this, the trouble starts when working with the actual data.

To reproduce it, launch [this example](https://github.com/jgvictores/2018-ptmr/blob/1f708efa7ea4dca1a9fd6bb0f898f35ea4a9763f/map1/openrave/ptmrSim1) and make the robot face a *wall*, looking in the direction of the *y* axis. Pixel values won't change if the sensor is translated along said axis. To make this even more obvious, focus the same wall from an oblique angle (values won't change either if belonging to the same plane), or try with [slopes](https://github.com/jgvictores/2018-ptmr/tree/1f708efa7ea4dca1a9fd6bb0f898f35ea4a9763f/map7).

While debugging, I learned that sensor data (`sensorRanges`) resolves to a matrix of zeroes, which leads me to think that it's more an OpenRAVE than a YARP issue.

https://github.com/roboticslab-uc3m/openrave-yarp-plugins/blob/e27f1cfb74b7f98ca805ccdd1663c6fd9a14ed6e/libraries/YarpPlugins/YarpOpenraveRGBDSensor/IRGBDSensorImpl.cpp#L72

**Comment by jgvictores** [comment]
Did a quick try via `python openraveYarpPluginLoader-rgbdsensor-noRGB.py `. Ports are open, but get error:
```
[INFO]created device <YarpOpenraveRGBDSensor>. See C++ class roboticslab::YarpOpenraveRGBDSensor for documentation.
[ERROR]RGBD wrapper: error configuring interfaces for parsers 
[ERROR]RGBDSensorWrapper: error while opening subdevice
yarpdev: ***ERROR*** driver <RGBDSensorWrapper> was found but could not open
[info] DeviceDriverImpl.cpp:134 close(): 
[error] OpenraveYarpPluginLoader.cpp:241 Open(): yarp plugin not valid.
None
```
Anything similar on your side?

**Comment by PeterBowman** [comment]
No, it works for me.

(@jgvictores) **Edit:** tested on YARP 2.3.72, but you might have hit https://github.com/robotology/yarp/pull/1633 (current master).

**Comment by jgvictores** [comment]
YARP 5bc7bfb7958b77a8655e390e05b82e993869cb92, OpenRAVE 7c5f5e27eec2b2ef10aa63fbc519a998c276f908 (current master), o-y-p e27f1cfb74b7f98ca805ccdd1663c6fd9a14ed6e (current develop).

Can you replicate the following screenshots?
![view1](https://user-images.githubusercontent.com/4448588/40630360-7234362c-62d2-11e8-9665-64c0cda240a2.png)
![view2](https://user-images.githubusercontent.com/4448588/40630365-76359216-62d2-11e8-949c-f86e1ef383b9.png)
![view3](https://user-images.githubusercontent.com/4448588/40630367-79f0fda0-62d2-11e8-972a-4115fb45bbed.png)

**Comment by PeterBowman** [comment]
Looks pretty much the same. Using YARP 2.3.72, OpenRAVE 7c5f5e2 and current develop of this repo.

| OpenRAVE | yarpview |
| :-------------: | :-------------: |
| ![1a](https://user-images.githubusercontent.com/9977198/40630503-6b75a874-62d3-11e8-94c0-44b1b465e45b.png) | ![1b](https://user-images.githubusercontent.com/9977198/40630504-6b91a77c-62d3-11e8-8c66-068ea29558be.png) |
| ![2a](https://user-images.githubusercontent.com/9977198/40630505-6baae336-62d3-11e8-91bc-1313ad0ee8be.png) | ![2b](https://user-images.githubusercontent.com/9977198/40630506-6bc63550-62d3-11e8-87de-7b8122e4516b.png) |
| ![3a](https://user-images.githubusercontent.com/9977198/40630508-6be1dc6a-62d3-11e8-8148-ab7bcd32edc9.png) | ![3b](https://user-images.githubusercontent.com/9977198/40630509-6bfe154c-62d3-11e8-9823-40b74886806a.png) |

**Comment by PeterBowman** [comment]
Note to self: http://openrave.org/docs/latest_stable/coreapihtml/classOpenRAVE_1_1SensorBase_1_1LaserSensorData.html.

**Comment by jgvictores** [comment]
Note to self: https://github.com/personalrobotics/offscreen_render

**Comment by PeterBowman** [comment]
> While debugging, I learned that sensor data (sensorRanges) resolves to a matrix of zeroes

No longer observing this behavior, but depth is still wrong.

**Comment by jgvictores** [comment]
Much better thanks to #88 !!
![photo_2018-05-30_16-52-22](https://user-images.githubusercontent.com/4448588/40735116-a28222ee-643a-11e8-856d-3a30b3c8ac08.jpg)
