### ISSUE TITLE
RGBD sensor plugin must implement yarp::dev::IFrameGrabberControls(2)

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/openrave-yarp-plugins#92]
Since YARP 2.3.72.1, [`yarp::dev::RGBDSensorWrapper`](http://www.yarp.it/classyarp_1_1dev_1_1RGBDSensorWrapper.html) expects that its wrapped subdevices implement `yarp::dev::FrameGrabberControls2` ([`yarp::dev::FrameGrabberControls`](http://www.yarp.it/classyarp_1_1dev_1_1IFrameGrabberControls.html) since YARP 3.0).

**Comment by PeterBowman** [comment]
See https://github.com/robotology/yarp/issues/1875.

**Comment by PeterBowman** [comment]
The aforementioned interface will be made optional at YARP 3.1.1 thanks to https://github.com/robotology/yarp/pull/1878. Anyway, our plugin will remain broken for 2.3.72.1, 3.0.0, 3.0.1 and 3.1.0.

**Comment by PeterBowman** [comment]
YARP v3.1.1 was released today.

**Comment by jgvictores** [comment]
@PeterBowman Thanks!!

**Comment by jgvictores** [comment]
https://www.frontiersin.org/articles/10.3389/frobt.2018.00040/full
